# FROM molguin/echoserver:binary
FROM molguin/redes:2022-1-T2

RUN apt-get update && \
    apt-get install iperf3 net-tools bash zsh python3 \
    python3-pip python3-virtualenv traceroute iputils-ping\
    build-essential -y